name: notebook_to_md

on:
  # External webhook trigger
  #repository_dispatch:
  # types: [push-notebook]
  pull_request

jobs:
  commit-notebooks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout site
        uses: actions/checkout@v3
        with:
          submodules: recursive # Fetch Hugo themes and all extra projects
          fetch-depth: 0 # Fetch all history for .GitInfo and .Lastmod
          path: site

      - name: Checkout coast
        uses: actions/checkout@v3
        with:
          repository: British-Oceanographic-Data-Centre/COAsT
          ref: develop
          path: external

      - name: Prepare environement
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: "3.8"
        run: |
          cd $GITHUB_WORKSPACE/external
          apt install wget unzip -y
          conda install cartopy
          wget https://linkedsystems.uk/erddap/files/COAsT_example_files/COAsT_example_files.zip
          unzip COAsT_example_files.zip && mv COAsT_example_files ./example_scripts/notebooks/runnable_notebooks/example_files
          python -m pip install .
          mv config ./example_scripts/notebooks/runnable_notebooks/config
          bash notebook_to_md.sh

      - name: covert notebooks
        run: |
          cd $GITHUB_WORKSPACE/external
          bash notebook_to_md.sh
          mv $GITHUB_WORKSPACE/external/example_scripts/notebooks/markdown/* $GITHUB_WORKSPACE/site/content/en/docs/Examples/Notebooks/

      - name: commit changes
        run: |
          echo "hello"
          git pull